#!/usr/bin/env bash
# Bash script to print the output of dig command
# Usage: ./0-world_wide_web <domain> and/or <subdomain>
# Output: The subdomain [SUB_DOMAIN] is a [RECORD_TYPE] record and points to [DESTINATION]

if [ $# -lt 1 ]; then
    exit 0
fi

domain_info() {
    line=$(dig "$2.$1" | grep -A1 'ANSWER SECTION' | grep "$2")
    echo "$2 $line" | awk '{print "The subdomain", $1, "is a", $5, "record and points to", $6}'
}

if [ $# -eq 1 ]; then

    subdomains=("www" "lb-01" "web-01" "web-02")

    for sub in "${subdomains[@]}"; do
        domain_info "$1" "$sub"
    done

elif [ $# -gt 1 ]; then
    domain_info "$1" "$2"
fi
