#!/usr/bin/env bash
# Basch script to install and configure Nginx on server

# installing Nginx
sudo apt update -y
sudo apt install nginx -y

# modefing the ownership and permissions of /var/www/ directory
sudo chown -R "$USER:$USER" /var/www/
sudo chmod -R 755 /var/www

# configure Nginx default page
echo "Hello World!" > /var/www/html/index.nginx-debian.html

# Allowing Nginx on the fire-wall
ufw allow 'Nginx HTTP'

# restarting nginx
sudo service nginx restart

