#!/usr/bin/env bash
# Script that configures a new ubuntu machine to install Nginx and redirection

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo chown -R ubuntu /var/www
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo sed -i "/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-enabled/default
sudo service nginx restart
