#!/usr/bin/env bash
#Not Found page 404

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo chown -R ubuntu /var/www
echo "Ceci n'est pas une page" > /var/www/html/404.html

sudo sed -i "25i\       error_page 404 /404.html;" /etc/nginx/sites-available/default

sudo service nginx restart
