#!/usr/bin/env bash
# Script that configures a new ubuntu machine to install Nginx and redirection

# Installing Nginx on the ubuntu server
sudo apt-get update -y
sudo apt-get install nginx -y

# Allowing the Ngnix on the Fire-wall
sudo ufw allow 'Nginx HTTP'

# Modifying the permissions of Ngnix document root directories to work on it without sudo
sudo chown -R "$USER:$USER" /var/www/html/
sudo chmod -R 755 /var/www/

# Writing the required text in the task into the index file
echo "Hello World!" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Using sed command to insert redirection action for /redirect_me path
sudo sed -i "/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-enabled/default
sudo sed -i "/listen 80 default_server/a error_page 404 /404.html;" /etc/nginx/sites-enabled/default

# Restarting Nginx and the Fire-wall so our modifications gey applied
service nginx restart
service nginx -t
