#!/usr/bin/env bash
# Bash script to Install and configure HAproxy on your lb-01 server.

# Installing HAProxy
sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.8
sudo apt-get install haproxy=2.8.\*

# Configure the HAProxy

echo "ENABLED=1" >/etc/default/haproxy

# Listen to web1 and web2 servers

echo "
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 505347-web-01 100.26.231.127:80 check
   server 505347-web-02 54.237.53.225:80 check
" >>/etc/haproxy/haproxy.cfg

service haproxy start
