#!/usr/bin/env bash
# Bash script that pings an IP address passed as an argument.
# - Displays Usage: 5-is_the_host_on_the_network {IP_ADDRESS} if no argument passed
# - Ping the IP 5 times

ARGS_ERR=1

if [ $# -ne 1 ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit $ARGS_ERR
fi

ping -c 5 "$1"
