#!/usr/bin/env bash
# Bash script to install Nginx on docker ubuntu container
# Nginx listening on port 80 (Default port)

sudo apt-get update -y
sudo apt-get install nginx -y
sudo apt-get install curl -y
sudo service nginx restart
