#!/usr/bin/env bash

sudo touch /var/run/myscript.pid
sudo chmod 666 var/run/myscript.pid
sudo echo "$$" > /var/run/myscript.pid

trap "echo 'I hate the kill command'; sudo rm /var/run/myscript.pid; exit" SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
trap "sudo rm /var/run/myscript.pid; exit" SIGQUIT
while true; do
    echo "To infinity and beyond"
    sleep 2 
done
