#!/usr/bin/env bash
# Bash script that groups visitors by IP and HTTP status code

# awk '{ count[$1 " " $9]++ } END { for (element in count) print count[element], element}' apache-access.log | sort -k1nr
# this code works but it gives checker error because of the lexicographic sorting between the IPs - HTTP status code of the same occurences

file="apache-access.log"

awk '{print $1 " " $9}' "$file" | sort | uniq -c | sort -nr
