#!/usr/bin/env bash
# a Bash script that displays:

# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed

for file in * ; do

    if [ -f "$file" ] && [ ! -d "$file" ] && [[ "$file" != .* ]]
    # checking if it is a file, not a direectory, does not start with a dot (hidden file)
    # The double brackets [[ ... ]] are used for pattern matching and additional operators.
    then
        echo "$file" | cut -d "-" -f2-
    fi
done
