#!/usr/bin/env bash
# script to configure ufw

sudo ufw default deny incoming
sudo ufw default deny outgoing

# Allow the necessary ports (SSH, HTTPS, and HTTP):
sudo ufw allow 22/tcp  # SSH
sudo ufw allow 443/tcp  # HTTPS
sudo ufw allow 80/tcp  # HTTP

# Apply the rules:
sudo service ufw restart
