#!/usr/bin/env bash
# Bash script that displays Best School

for (( i = 1; i <= 100; i++ ))
do
    if [[ $((i % 3)) -eq 0 && $((i % 5)) -eq 0 ]]; then
        echo "FizzBuzz"
    elif ((i % 3 == 0)) && ((i % 5 != 0)); then
        echo "Fizz"
    elif ((i % 3 != 0)) && ((i % 5 == 0)); then
        echo "Buzz"
    else
        echo "$i"
    fi
done
