#!/usr/bin/env bash
#Bash script that displays Best School

i=0
while [[ $i -lt 10 ]]
do
    if [ $i = 8 ]; then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi
    i=$(( i + 1))
done
