#!/usr/bin/env bash
#Write a Bash script that displays The content of the current directory


for file in *
do
    if [ -f "$file" ] && [ ! -d "$file" ] && [[ "$file" != .* ]]
    then
        name=$(echo "$file" | cut -d'-' -f2-)
        echo "$name"
    fi

done
